trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistry: 'your-docker-registry'
  imageName: 'multi-agent-ai-system'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistry)'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
